### ISSUE TITLE
"./site build" error

### ISSUE THREAD

**Issue by luckypoem** [michaelsproul/sproul.xyz#1]
hi.

root@AR:/usr/local/sproul.xyz# ./site build
Initialising...
  Creating store...
  Creating provider...
  Running rules...
Checking for out-of-date items
Compiling
  updated templates/base.html
  updated 404.html
  updated about.md
  updated css/fonts/social_foundicons.eot
  updated css/fonts/social_foundicons.svg
  updated css/fonts/social_foundicons.ttf
  updated css/fonts/social_foundicons.woff
  [ERROR] sassc: createProcess: runInteractiveProcess: exec: does not exist (No such file or directory)
root@AR:/usr/local/sproul.xyz# sass --version
Sass 3.4.22 (Selective Steve)
root@AR:/usr/local/sproul.xyz#

how to fix it?

**Comment by michaelsproul** [comment]
I think `sassc` might be a separate package. You could either try looking in your OS's package manager for it, or changing the line in the Haskell file to `sass`.

**Comment by michaelsproul** [comment]
For reference, I use version 3.3.0 of Sass from the `sassc` Homebrew package for OS X

**Comment by luckypoem** [comment]
hi,

as per this article: https://yami.io/sassc/ , i installed sassy.

root@AR:~# sassc --version
sassc: 3.3.6-30-g5472
libsass: 3.4.0-RC1
sass2scss: 1.1.0
sass: 3.4
root@AR:~# cd /usr/local/sproul.xyz
root@AR:/usr/local/sproul.xyz# ./site build
Initialising...
  Creating store...
  Creating provider...
  Running rules...
Checking for out-of-date items
Compiling
  cached  templates/base.html
  cached  404.html
  cached  about.md
  updated css/fonts/social_foundicons.eot
  updated css/fonts/social_foundicons.svg
  updated css/fonts/social_foundicons.ttf
  updated css/fonts/social_foundicons.woff
  updated css/icons/social_foundicons.css
  updated css/icons/social_foundicons_ie7.css
  updated css/syntax.css
  updated favicon.ico
  updated foundation/_foundation-global.scss
  updated foundation/custom.scss
  [ERROR] Hakyll.Core.UnixFilter.unixFilterWith: sassc -s gave exit code 1
root@AR:/usr/local/sproul.xyz#

still there is error.how to fix it?

in my mac,i run "brew install sassc",then i installed ur app successfully.but in my debian vps,i failed.
very weird.

**Comment by michaelsproul** [comment]
It might be a sass version issue, a while ago I had to debug this and ended up using `Debug.Trace` to find out which file was failing, then ran sassc on that file manually. If I get a chance I'll look into making the running of sass more transparent

**Comment by luckypoem** [comment]
hello.

i installed ur app successfully in my mac then upload _site's contents to my linux vps.

i see here: https://github.com/ericrasmussen/chromaticleaves/issues/1 ,u forked from https://github.com/ericrasmussen/chromaticleaves ,

here: https://github.com/ericrasmussen/chromaticleaves/issues/2 ,i submit my issue,but the author didn't reply me, could u pls kindly tell me how to fix it?

**Comment by michaelsproul** [comment]
I think I fixed that by importing `defaultTimeLocale` from `Data.Time.Format` rather than `System.Locale`. See here:

https://github.com/michaelsproul/sproul.xyz/commit/06cf3473933d25fa2a99f0ff206159010ec95900

**Comment by luckypoem** [comment]
hi.

this time i ran "ghc --make site.hs",encountered no error.the executable file "site" is generated.
root@AR:/usr/local/chromaticleaves-site# ls
404.html	       css	   index.html  scores	slides
about.markdown	       dist	   js	       site	templates
cabal.sandbox.config   explore	   LICENSE     site.hi
chromaticleaves.cabal  foundation  posts       site.hs
commands.markdown      images	   README.md   site.o
root@AR:/usr/local/chromaticleaves-site#  ./site build

it shows:
...
  [ERROR] Hakyll.Core.UnixFilter.unixFilterWith: sass -s --scss gave exit code 65
root@AR:/usr/local/chromaticleaves-site# 

but i already installed sass with "gem install sass",
root@AR:~# sass --version
Sass 3.4.22 (Selective Steve)
root@AR:~# 

do i have to install sass 3.3.0?

**Comment by luckypoem** [comment]
now i know how to do,
gem uninstall sass
gem install sass --version=3.3.0

then run " ./site build",i meet no error.

**Comment by michaelsproul** [comment]
ok cool, glad it's all working now

**Comment by luckypoem** [comment]
hi.

i feel u are a haskell expert.i found this repo: https://github.com/maseek/maseek-codes ,
here: https://github.com/maseek/maseek-codes/blob/master/src/site.hs ,
i cloned this repo,and modified its site.hs:
i deleted this line: import System.Locale (defaultTimeLocale)
and added a new line: import Data.Time.Format (formatTime, defaultTimeLocale)

but running "ghc --make site.hs" encounter another error:

root@AR:/usr/local/maseek.codes/src# ghc --make site.hs
[1 of 1] Compiling Main ( site.hs, site.o )

site.hs:191:45: error:
• Couldn't match expected type ‘Item Text.Pandoc.Definition.Pandoc’
with actual type ‘Compiler (Item Text.Pandoc.Definition.Pandoc)’
• In the second argument of ‘($)’, namely ‘readPandoc item’
In the second argument of ‘($)’, namely
‘writePandoc $ readPandoc item’
In the expression: return $ writePandoc $ readPandoc item
root@AR:/usr/local/maseek.codes/src#
(pls see https://github.com/maseek/maseek-codes/issues/1)

could u help me fix the error?
thank u!
